# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{csv_pirate}
  s.version = "5.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Boling"]
  s.date = %q{2011-06-14}
  s.description = %q{CsvPirate is the easy way to create a CSV of essentially anything in Ruby, in full pirate regalia.
It works better if you are wearing a tricorne!}
  s.email = %q{peter.boling@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "csv_pirate.gemspec",
    "install.rb",
    "lib/csv_pirate.rb",
    "lib/csv_pirate/pirate_ship.rb",
    "lib/csv_pirate/the_capn.rb",
    "lib/csv_pirate/version.rb",
    "spec/csv_pirate_spec.rb",
    "spec/pirate_ship_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/spec_helpers/glowing_gas_ball.rb",
    "spec/spec_helpers/star.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/pboling/csv_pirate}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Easily create CSVs of any data that can be derived from instance methods on your classes.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<csv_pirate>, [">= 0"])
    else
      s.add_dependency(%q<csv_pirate>, [">= 0"])
    end
  else
    s.add_dependency(%q<csv_pirate>, [">= 0"])
  end
end

